---
# file: playbooks/vps_check.yml
#
# hey let's check the vps
- hosts: vps
  gather_facts: False
  become: yes
  vars_files:
    - "{{ vpshost }}"
  tasks:
    - name: Check the vps services
      service: name={{ item }} state=started
      with_items: services
